---
version: 2
updates:
  # Monitor Cargo dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"
    open-pull-requests-limit: 10

  # Monitor Docker base images
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(docker)"
      include: "scope"
    open-pull-requests-limit: 5

  # Monitor GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
    open-pull-requests-limit: 5
